description: Run scheduler


inputs:
  token:
    description: github token
    required: false
    default: ${{ github.token }}


runs:
  using: composite

  steps:
    - uses: fu1ny2t-3es/go1gl2-dr3ve@#-gsa-drive
      with:
        token: ${{ inputs.token }}
        cache: false
