description: manage gdrive


inputs:
  token:
    description: github token
    required: false

  drive:
    description: specific drive
    required: false

  cache:
    description: first time run
    required: false


runs:
  using: composite

  steps:
  - uses: fu1ny2t-3es/gi1-ac2io3s@checkout-branch
    with:
      repository: fu1ny2t-3es/go1gl2-dr3ve
      branch: "#-gsa-drive"

      token: ${{ inputs.token }}
      auto: true
  
  
  - uses: actions/setup-python@main


  - shell: bash
    working-directory: ${{ github.workspace }}
    run: |
      python -m pip install --upgrade pip
      pip install build twine



  - shell: bash
    working-directory: ${{ github.workspace }}
    run: |
      python -m pip install requests
      python -m pip install pycron
      python -m pip install fire
      python -m pip install bs4
      python -m pip install pyotp
      python -m pip install pydrive
      python -m pip install tqdm
      python -m pip install requests_toolbelt
      python -m pip install google


  - shell: bash
    working-directory: ${{ github.workspace }}
    run: |
      mkdir keys
      cd keys
      curl -L https://github.com/${{ github.repository }}/raw/secret/keys.7z > keys.7z
      7za x -p${{ env.keys_password }} keys.7z

      cd ..
      python -u drive.py ${{ env.drive_copy }} > log.txt

      7za a log.7z log.txt -p${{ env.password }}
